### ISSUE TITLE
Few results despite good data

### ISSUE THREAD

**Issue by CharlotteAnne** [skrakau/PureCLIP#10]
Hi! I am running pureCLIP in basic mode on some very nice quality data, but it doesn't seem to be capturing the best binding regions, which I have observed using other methods.

Could you give me any tips on the settings that I should be checking and tweaking, because I'm not very clear on what I should be adjusting?

Thanks in advance for your help! - Charlotte

**Comment by skrakau** [comment]
Hi Charlotte,

sorry for the late reply! It is difficult to answer that question without knowing any details. How did you run PureCLIP, e.g. with or without input data, CL-bias correction etc. ? How do you define 'best binding regions' and what are the other methods (peak calling or crosslink site detection)? 

Another question would be what are the binding and signal characteristics of your protein of interest? For example, does it bind to a locally defined region and cause clear truncation patterns or does it rather cause evenly distributed read starts? Depending on that, for example, a different scoring scheme might be helpful (see [https://github.com/skrakau/PureCLIP/issues/9](https://github.com/skrakau/PureCLIP/issues/9) ).

If you have further questions or some specific cases causing problems let me know. 

Best,
Sabrina

**Comment by skrakau** [comment]
I will close this issue, for further questions feel free to contact me via email.
