### ISSUE TITLE
reference genome can not be load

### ISSUE THREAD

**Issue by qicaibiology** [skrakau/PureCLIP#12]
Hi All:

I am doing CLIP-seq analysis following the manual of [PureCLIP][1]: 
I have 2 problems which I can not solve so far:

#1 getting the reference genome:

    (base) [caiqi@midway2-login2 genome_fa]$ gunzip ref.GRCh38.fa.gz  
    
    gzip: ref.GRCh38.fa.gz: unexpected end of file
    (base) [caiqi@midway2-login2 genome_fa]$ zcat ref.GRCh38.fa.gz > ref.GRCh38.fa
    
    gzip: ref.GRCh38.fa.gz: unexpected end of file

So I tried to get the reference genome from the iGenome website to do the STAR mapping and other preprocessing. Everything goes well untilI am about to use the package for analysis:

#2: using the .fa file for analysis

    (base) [caiqi@midway2-login2 PUM2_CLIP]$ pureclip -i aligned.f.duplRm.pooled.R2.bam -bai aligned.f.duplRm.pooled.R2.bam.bai -g ref.GRCh38.fa -iv 'chr1;chr2;chr3;' -nt 10 -o PureCLIP.crosslink_sites.bed
    
    Protein-RNA crosslink site detection 
    ===============
    
    Created look-up table for values from -2000 to 0 with step size 0.00333333 (size: 600000).
    Loading reference ... 
    ERROR: Can't load reference sequence from file 'ref.GRCh38.fa': Unexpected character 'M' found. 

Can anyone help me out for these 2 bugs?

Thanks a lot,

Cai

**Comment by skrakau** [comment]
Hi,

1) it seems that your download failed because the link for the GENCODE reference file changed.  This should work: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/GRCh38.primary_assembly.genome.fa.gz  

2) The problem is coming from an external library which is used and which expects the reference sequence to contain only the letters 'A', 'C', 'G', 'T' or 'N'. I know it is not ideal, but if you convert all non-ACGTs to Ns, the problem should be solved.

I hope this helps.

**Comment by qicaibiology** [comment]
> Hi,
> 
> 1. it seems that your download failed because the link for the GENCODE reference file changed.  This should work: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/GRCh38.primary_assembly.genome.fa.gz
> 2. The problem is coming from an external library which is used and which expects the reference sequence to contain only the letters 'A', 'C', 'G', 'T' or 'N'. I know it is not ideal, but if you convert all non-ACGTs to Ns, the problem should be solved.
> 
> I hope this helps.

excuse me I tried it again today, and I an wondering how to convert the non-AGCT to Ns?
