### ISSUE TITLE
call peaks after PureClip analysis

### ISSUE THREAD

**Issue by qicaibiology** [skrakau/PureCLIP#13]
Hi:

I don't know if it is appropriate to ask a question on the downstream analysis of pureclip. If it is not, please let me know and I will delete it.

I have used PureClip to analyze the an eClip-seq dataset and get the bedfile. Now I want to get the binding motif of the RBP, so I installed MEME to call motif from the bedfile.

The head of my bed file is like this:
`head file.bed`

> chr1 633991 633992 3 14.891 + [score_CL=14.891;score_E=55.5259;score_B=56.5133;score_UC=14.891] 

`bedtools getfasta -fi GRCh38.primary_assembly.genome.fa -bed file.bed -s -fo file.fasta`
`meme file.fasta -mod anr -o RBP_MEME_anr_motif6 -rna -nmotifs 6 >log015 2>error015`

> Writing results to output directory 'PureCLIP_HNRNPK_MEME_anr_motif6'. BACKGROUND: using background model of order 0 PRIMARY (classic): n 13474 p0 13474 p1 0 p2 0 SEQUENCE GROUP USAGE-- Starts/EM: p0; Trim: p0; pvalue: p0; nsites: p0,p1,p2 All sequences must be at least 8 characters long. Set '-w' or '-minw' or remove shorter sequences and rerun.

Thank you for anyone that can help!

**Comment by skrakau** [comment]
I guess the reason is that `bedtools getfasta` extracts exactly the regions specified in your bed file, i.e. in your case of length 1bp. If you want a larger window you could extend the regions, for example, with `awk 'BEGIN{FS=OFS="\t"} {print $1, ($2-5), ($3+5), $4, $5, $6}' file.bed > file_windows.bed` (take care when having crosslink sites close to the sequence ends), but I think there is also a bedtools option for this.

**Comment by qicaibiology** [comment]
> I guess the reason is that `bedtools getfasta` extracts exactly the regions specified in your bed file, i.e. in your case of length 1bp. If you want a larger window you could extend the regions, for example, with `awk 'BEGIN{FS=OFS="\t"} {print $1, ($2-5), ($3+5), $4, $5, $6}' file.bed > file_windows.bed` (take care when having crosslink sites close to the sequence ends), but I think there is also a bedtools option for this.

Thank you very much for the reply. I did it like you said. What do you mean by saying: "take care when having crosslink sites close to the sequence ends), but I think there is also a bedtools option for this".  What is the coveat for doing this? I suppose the 1nt is close to the sequence ends by eclip-seq?
Thanks you,

**Comment by skrakau** [comment]
I actually just meant the reference, but it is probably only relevant if you use transcripts as references: for example, if there is a crosslink site at the beginning of your reference you might end up with negative positions when using the awk command from above (0-5 -> -5), which would likely cause problems with bedtools.
