### ISSUE TITLE
wish your advice about pipeline

### ISSUE THREAD

**Issue by gnilihzeux** [skrakau/PureCLIP#5]
why there're no UMI step before STAR alignment ? Didn't  UMI sequences affect the alignment?

**Comment by skrakau** [comment]
It depends on the data if the UMIs are still part of the read sequences or not. In case of the ENCODE eCLIP FASTQ files, they are already removed from the sequences and included into the read ID. 
Otherwise this still needs to be done.

**Comment by gnilihzeux** [comment]
Thank you very much. It seems there're more steps before mapping.
