### ISSUE TITLE
Issue with Binding Region output

### ISSUE THREAD

**Issue by natsampaio** [skrakau/PureCLIP#8]
Hello!

I am running pureCLIP to analyse my iCLIP data, and it seems to call crosslinking sites well. However, the binding regions output is giving me the same region as crosslinking, i.e. each 'region' is still just 1 nucleotide in length. I have tried using the default distance parameter (8 nt), as well as increasing to 10 and 20 nt, but I still get the same results.

$ pureclip -i IP2.dedup.bam -bai IP2.dedup.bam.bai -g /t1-data/user/nsampaio/Databases/hg38_EMCV.fasta -iv 'chr1;chr2;chr3;chr4;chr5;chr6' -nt 8 -o Crosslink_sites.2.bed -or Binding_regions.2.bed -bc 1 -antp -ibam SMI.IP2.dedup.bam -ibai SMI.IP2.dedup.bam.bai      -nim 4 -fis IP2.dedup.bam.CLmotif.bed

Here are the two files I obtain:

$ head Binding_regions.2.bed 
chr1	633769	633770	3.22984;	3.22984	+
chr1	11908229	11908230	4.78712;	4.78712	+
chr1	40072181	40072182	1.32633;	1.32633	+
chr1	109727065	109727066	5.5488;	5.5488	+
chr1	146039431	146039438	3.07453;10.9513;	14.0259	+
chr1	153671302	153671303	2.26636;	2.26636	+
chr1	244992012	244992015	5.25178;2.58477;	7.83655	-
chr1	237945635	237945636	12.1183;	12.1183	-
chr1	237945624	237945625	1.47711;	1.47711	-
chr1	237943912	237943913	7.60038;	7.60038	-

$ head Crosslink_sites.2.bed 
chr1	633769	633770	3	3.22984	+
chr1	11908229	11908230	3	4.78712	+
chr1	40072181	40072182	3	1.32633	+
chr1	109727065	109727066	3	5.5488	+
chr1	146039431	146039432	3	3.07453	+
chr1	146039437	146039438	3	10.9513	+
chr1	153671302	153671303	3	2.26636	+
chr1	244992014	244992015	3	5.25178	-
chr1	244992012	244992013	3	2.58477	-
chr1	237945635	237945636	3	12.1183	-

Some help would be greatly appreciated.

Kind Regards,

Natalia

**Comment by skrakau** [comment]
Hi Natalia,

For the binding region output PureCLIP merges only called crosslink sites. That is why for a lot of sites, which have no other called crosslink site within close proximity,  the output is the same.  

However, the sites 
chr1	146039431	146039432	3	3.07453	+
chr1	146039437	146039438	3	10.9513	+
are merged to
chr1	146039431	146039438	3.07453;10.9513;	14.0259	+

And
chr1	244992014	244992015	3	5.25178	-
chr1	244992012	244992013	3	2.58477	-
became
chr1	244992012	244992015	5.25178;2.58477;	7.83655	-

Best,
Sabrina
